### ISSUE TITLE
userwidget绑定lua后，无法被gc系统正常销毁

### ISSUE THREAD

**Issue by unicodecndddd** [Tencent/UnLua#123]
对绑定过lua的userwidget调用RemoveFromViewport过后，lua文件依然留在lua注册表中。不知道有没有提供类似AActor的K2_DestroyActor的强制销毁方法。

**Comment by unicodecndddd** [comment]
似乎和这个问题 #73 是一样，请问现在有解决方案了吗？

**Comment by rowechien** [comment]
@unicodecndddd fixed in [5df8813](https://github.com/Tencent/UnLua/commit/ccaa2bd8d60ec3d391bed2f8fe9207d4a5354042)
以删除一个UserWidget实例为例：
![image](https://user-images.githubusercontent.com/7972243/76141008-575afe80-609b-11ea-9203-1f841a888780.png)
在destroy前最好把添加在它上面的delegate都清理干净，当然不清理也没关系。。。
如果整个UserWidget类都不用了，可以这样：
![image](https://user-images.githubusercontent.com/7972243/76141003-490ce280-609b-11ea-98d1-e43576eb3a5f.png)
