### ISSUE TITLE
4.25.4编译失败，支持4.25吗？

### ISSUE THREAD

**Issue by xpc-yx** [Tencent/UnLua#218]
RT

**Comment by blackplume233** [comment]
https://git.code.tencent.com/blackplume/Tencent_unlua  你可以去这个库上下载

**Comment by blackplume233** [comment]
如果你还有需求的话

**Comment by dlwcry** [comment]
> https://git.code.tencent.com/blackplume/Tencent_unlua 你可以去这个库上下载

这里面的代码还是旧的吧，还是没有整理代码时候的目录接口。
反射信息都集中在一个文件里面。

**Comment by blackplume233** [comment]
> > https://git.code.tencent.com/blackplume/Tencent_unlua 你可以去这个库上下载
> 
> 这里面的代码还是旧的吧，还是没有整理代码时候的目录接口。
> 反射信息都集中在一个文件里面。

这里面的代码和GitHub库里的代码版本是一致的，只是解决了在4.25上的一些编译报错。如果你有最新版本希望可以提交

**Comment by dlwcry** [comment]
> > > https://git.code.tencent.com/blackplume/Tencent_unlua 你可以去这个库上下载
> > 
> > 
> > 这里面的代码还是旧的吧，还是没有整理代码时候的目录接口。
> > 反射信息都集中在一个文件里面。
> 
> 这里面的代码和GitHub库里的代码版本是一致的，只是解决了在4.25上的一些编译报错。如果你有最新版本希望可以提交

你好，不好意思，我刚刚又确认了一遍，确实是旧版本

我下载了工蜂里的 master 的，对比 github 上的 master 差别很大，

工蜂上还有 UEReflectionUtils.cpp 这个文件
而 github 上的早就被拆成 ClassDesc;FunctionDesc;PropertyDesc 不同的文件了

**Comment by blackplume233** [comment]
Soga那有可能是我用错版本了 李嘉豪 邮箱：blackplume233@gmail.com 签名由 网易邮箱大师 定制 在2020年11月30日 16:59，dlwcry 写道： https://git.code.tencent.com/blackplume/Tencent_unlua 你可以去这个库上下载 这里面的代码还是旧的吧，还是没有整理代码时候的目录接口。 反射信息都集中在一个文件里面。 这里面的代码和GitHub库里的代码版本是一致的，只是解决了在4.25上的一些编译报错。如果你有最新版本希望可以提交 你好，不好意思，我刚刚又确认了一遍，确实是旧版本 我下载了工蜂里的 master 的，对比 github 上的 master 差别很大， 工蜂上还有 UEReflectionUtils.cpp 这个文件 而 github 上的早就被拆成 ClassDesc;FunctionDesc;PropertyDesc 不同的文件了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by blackplume233** [comment]
> Soga那有可能是我用错版本了 李嘉豪 邮箱：blackplume233@gmail.com 签名由 网易邮箱大师 定制 在2020年11月30日 16:59，dlwcry 写道： https://git.code.tencent.com/blackplume/Tencent_unlua 你可以去这个库上下载 这里面的代码还是旧的吧，还是没有整理代码时候的目录接口。 反射信息都集中在一个文件里面。 这里面的代码和GitHub库里的代码版本是一致的，只是解决了在4.25上的一些编译报错。如果你有最新版本希望可以提交 你好，不好意思，我刚刚又确认了一遍，确实是旧版本 我下载了工蜂里的 master 的，对比 github 上的 master 差别很大， 工蜂上还有 UEReflectionUtils.cpp 这个文件 而 github 上的早就被拆成 ClassDesc;FunctionDesc;PropertyDesc 不同的文件了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

soga我发现了 我应该从Github上去拉分支，工蜂上不维护的事件更长了，那我们可以尝试去维护下这个最新的版本，尽管也已经很老旧了

**Comment by rowechien** [comment]
@xpc-yx 我在4.25.3下编译是正常的，按理来说在25.4下也不会有问题啊。。。

**Comment by rowechien** [comment]
@xpc-yx 我下了个干净的4.25.4，编译也没有问题啊。有没有详细的报错？？

**Comment by rowechien** [comment]
@xpc-yx 我这边确实没有发现编译错误，如果你的错误是这样的：
![image](https://user-images.githubusercontent.com/7972243/107194887-9623d200-6a2b-11eb-8dd7-ae7ce1e05eae.png)
你可以按引擎的提示去修改工程的build.cs文件。
如果不是这种错误，你可以reopen这个issue或者新开一个issue，然后提供详细的编译错误。
